### ISSUE TITLE
GreenPix organization Teams

### ISSUE THREAD

**Issue by ghost** [GreenPix/meta#2]
Hi everyone.

I propose the following teams for our organization:
- `Owners`: team with all possible powers. I propose to create a GreenPix account with a shared password and let it be the only member of this team. Hence, the organization is tied to the association and not its members.
- `Core Team`: team with admin right (allmost the same as Owners team, without billing info editing AFAIK). Can create repos, so we're good.
- `Contributors`: team with write accesses only. Cannot create repo but can commit and push to repos. Used for regular contributors.

Not that there is an issue here: `Contributors` gives rights to _every single repos we have_. That's probably not what we want, but it can happen. For more specific rights (eg. push to a _single_ repo) it's a repo-based configuration (Github permits this).

As for now, @Azamung stays in Owners team. If you disagree, I can rollback to preexisting organization (with everyone as Owner). If we all agree, I will create the account.

**Comment by Nemikolh** [comment]
Hello ! I'm not sure if I'm the only one to see that but the `Core Team` is marked as having zero repository and I can no longer merge/push to branches on either `sarosa`, `dilia` or `meta`.
Am I the only one to have this bug?
I guess it might have been caused by a github update.

Coming back to your proposal, I fully agree to it.

**Comment by ghost** [comment]
That's pretty anoying. I will try to fix this asap.

**Comment by Nemikolh** [comment]
Cool! Do you have the same issue?

**Comment by ghost** [comment]
Indeed I have. I put everyone back to Owners until I find out how to deal with this.

**Comment by ghost** [comment]
Okay so, here is why: https://github.com/blog/2064-new-organization-permissions-now-available

**Comment by Nemikolh** [comment]
Ok I think I found out how to add the repositories to the core team thanks to your link.
EDIT: Yeah, now it should be fine if you remove us from the core team

**Comment by ghost** [comment]
One question remains: will we able to create new repository and will we be able to push/commit/whatever to those repos?

**Comment by Nemikolh** [comment]
When we were only in the Core Team with zero repository I was able to create a repository but I didn't have write access to the other repository because they were only owned by the Owner Team. Now that the Core Team also owns them, I think it should be fine. You can give it a try, at worst we rollback to what we are now.

**Comment by ghost** [comment]
Let's do this. I have to create the association account, too.
